# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2018_07_13_085122) do

  create_table "amazon_financial_events", options: "ENGINE=InnoDB DEFAULT CHARSET=latin1", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "company_id"
    t.string "type"
    t.date "event_day"
    t.string "amazon_order_id"
    t.string "seller_order_id"
    t.string "marketplace_name"
    t.datetime "posted_date"
    t.float "fee_total"
    t.string "fee_currency_code"
    t.string "marketplace_country_code"
    t.string "asin"
    t.float "total_amount_currency_amount"
    t.string "total_amount_currency_code"
    t.float "order_charge_total"
    t.string "order_charge_currency_code"
    t.float "order_charge_adjustment_total"
    t.string "order_charge_adjustment_currency_code"
    t.float "shipment_fee_total"
    t.string "shipment_fee_currency_code"
    t.float "shipment_fee_adjustment_total"
    t.string "shipment_fee_adjustment_currency_code"
    t.float "order_fee_total"
    t.string "order_fee_currency_code"
    t.float "order_fee_adjustment_total"
    t.string "order_fee_adjustment_currency_code"
    t.float "direct_payment_total"
    t.string "direct_payment_currency_code"
    t.string "shipment_item_skus"
    t.string "business_object_type"
    t.string "sales_channel"
    t.string "charge_type"
    t.float "charge_amount_currency_amount"
    t.string "charge_amount_currency_code"
    t.string "payment_amount_type"
    t.string "amount_description"
    t.string "fulfillment_channel"
    t.string "store_name"
    t.string "provider_transaction_type"
    t.string "marketplace_id"
    t.string "seller_id"
    t.string "seller_store_name"
    t.string "provider_id"
    t.string "provider_store_name"
    t.string "retrocharge_event_type"
    t.string "rental_event_type"
    t.string "extension_length"
    t.float "rental_charge_total"
    t.string "rental_charge_currency_code"
    t.float "rental_fee_total"
    t.string "rental_fee_currency_code"
    t.float "rental_initial_value_currency_amount"
    t.string "rental_initial_value_currency_code"
    t.float "rental_reimbursement_currency_amount"
    t.string "rental_reimbursement_currency_code"
    t.float "rental_tax_withheld_total"
    t.string "rental_tax_withheld_currency_code"
    t.float "amount_currency_amount"
    t.string "amount_currency_code"
    t.string "product_groups"
    t.string "transaction_type"
    t.string "invoice_id"
    t.float "base_value_currency_amount"
    t.string "base_value_currency_code"
    t.float "tax_value_currency_amount"
    t.string "tax_value_currency_code"
    t.float "transaction_value_currency_amount"
    t.string "transaction_value_currency_code"
    t.string "fee_reason"
    t.string "seller_sku"
    t.string "fn_sku"
    t.string "fee_description"
    t.string "debt_recovery_type"
    t.float "recovery_amount_currency_amount"
    t.string "recovery_amount_currency_code"
    t.float "over_payment_credit_currency_amount"
    t.string "over_payment_credit_currency_code"
    t.float "loan_amount_currency_amount"
    t.string "loan_amount_currency_code"
    t.string "source_business_event_type"
    t.string "adjustment_type"
    t.float "adjustment_amount_currency_amount"
    t.string "adjustment_amount_currency_code"
    t.string "adjustment_item_skus"
    t.string "coupon_id"
    t.string "seller_coupon_description"
    t.integer "clip_or_redemption_count"
    t.string "payment_event_id"
    t.string "safet_claim_id"
    t.float "reimbursed_amount_currency_amount"
    t.float "reimbursed_amount_currency_code"
    t.string "enrollment_id"
    t.string "parent_asin"
    t.string "original_removal_order_id"
    t.float "liquidation_proceeds_amount_currency_amount"
    t.string "liquidation_proceeds_amount_currency_code"
    t.float "liquidation_fee_amount_currency_amount"
    t.string "liquidation_fee_amount_currency_code"
    t.string "imaging_request_billing_item_id"
    t.float "shipment_item_charge_total"
    t.string "shipment_item_charge_currency_code"
    t.float "shipment_item_charge_adjustment_total"
    t.string "shipment_item_charge_adjustment_currency_code"
    t.float "shipment_item_fee_total"
    t.string "shipment_item_fee_currency_code"
    t.float "shipment_item_promotion_total"
    t.string "shipment_item_promotion_currency_code"
    t.float "shipment_item_promotion_adjustment_total"
    t.string "shipment_item_promotion_adjustment_currency_code"
    t.float "shipment_item_points_granted_total"
    t.string "shipment_item_points_granted_currency_code"
    t.float "shipment_item_points_returned_total"
    t.string "shipment_item_points_returned_currency_code"
    t.float "shipment_item_tax_withheld_total"
    t.string "shipment_item_tax_withheld_currency_code"
    t.datetime "transaction_posted_date"
    t.float "base_tax_currency_amount"
    t.string "base_tax_currency_code"
    t.float "shipping_tax_currency_amount"
    t.string "shipping_tax_currency_code"
    t.float "shipment_item_fee_adjustment_total"
    t.string "shipment_item_fee_adjustment_currency_code"
    t.string "shipment_item_adjustment_skus"
    t.float "shipment_item_adjustment_charge_total"
    t.string "shipment_item_adjustment_charge_currency_code"
    t.float "shipment_item_adjustment_tax_withheld_total"
    t.string "shipment_item_adjustment_tax_withheld_currency_code"
    t.float "shipment_item_adjustment_charge_adjustment_total"
    t.string "shipment_item_adjustment_charge_adjustment_currency_code"
    t.float "shipment_item_adjustment_fee_total"
    t.string "shipment_item_adjustment_fee_currency_code"
    t.float "shipment_item_adjustment_fee_adjustment_total"
    t.string "shipment_item_adjustment_fee_adjustment_currency_code"
    t.float "shipment_item_adjustment_promotion_total"
    t.string "shipment_item_adjustment_promotion_currency_code"
    t.float "shipment_item_adjustment_promotion_adjustment_total"
    t.string "shipment_item_adjustment_promotion_adjustment_currency_code"
    t.float "shipment_item_adjustment_points_granted_total"
    t.string "shipment_item_adjustment_points_granted_currency_code"
    t.float "shipment_item_adjustment_points_returned_total"
    t.string "shipment_item_adjustment_points_returned_currency_code"
    t.index ["company_id"], name: "index_amazon_financial_events_on_company_id"
  end

  create_table "amazon_listings", options: "ENGINE=InnoDB DEFAULT CHARSET=latin1", force: :cascade do |t|
    t.string "sku"
    t.string "asin"
    t.string "title"
    t.bigint "company_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["company_id"], name: "index_amazon_listings_on_company_id"
  end

  create_table "amazon_order_items", options: "ENGINE=InnoDB DEFAULT CHARSET=latin1", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "amazon_order_id"
    t.string "tax_collection_model"
    t.string "tax_collection_responsible_party"
    t.integer "quantity_ordered"
    t.string "title"
    t.string "shipping_tax_currency_code"
    t.float "shipping_tax_amount"
    t.string "promotion_discount_currency_code"
    t.float "promotion_discount_amount"
    t.string "condition_id"
    t.boolean "is_gift"
    t.string "asin"
    t.string "seller_sku"
    t.string "order_item_id"
    t.string "product_info_number_of_items"
    t.string "gift_wrap_tax_currency_code"
    t.float "gift_wrap_tax_amount"
    t.integer "quantity_shipped"
    t.string "shipping_price_currency_code"
    t.float "shipping_price_amount"
    t.string "gift_wrap_price_currency_code"
    t.float "gift_wrap_price_amount"
    t.string "condition_subtype_id"
    t.string "item_price_currency_code"
    t.float "item_price_amount"
    t.string "item_tax_currency_code"
    t.float "item_tax_amount"
    t.string "shipping_discount_currency_code"
    t.float "shipping_discount_amount"
    t.index ["amazon_order_id"], name: "index_amazon_order_items_on_amazon_order_id"
    t.index ["order_item_id"], name: "index_amazon_order_items_on_order_item_id", unique: true
  end

  create_table "amazon_orders", options: "ENGINE=InnoDB DEFAULT CHARSET=latin1", force: :cascade do |t|
    t.string "buyer_email"
    t.string "buyer_name"
    t.bigint "company_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.datetime "latest_ship_date"
    t.string "order_type"
    t.datetime "purchase_date"
    t.boolean "is_replacement_order"
    t.datetime "last_update_date"
    t.string "amazon_order_id"
    t.integer "number_of_items_shipped"
    t.string "ship_service_level"
    t.string "order_status"
    t.string "sales_channel"
    t.boolean "shipped_by_amazon_tfm"
    t.boolean "is_business_order"
    t.datetime "latest_delivery_date"
    t.integer "number_of_items_unshipped"
    t.string "payment_method_details"
    t.string "earliest_delivery_date"
    t.boolean "is_premium_order"
    t.string "order_total_currency_code"
    t.float "order_total_amount"
    t.datetime "earliest_ship_date"
    t.string "marketplace_id"
    t.string "fulfillment_channel"
    t.string "payment_method"
    t.string "shipping_address_city"
    t.string "shipping_address_address_type"
    t.string "shipping_address_postal_code"
    t.string "shipping_address_state_or_region"
    t.string "shipping_address_country_code"
    t.string "shipping_address_name"
    t.string "shipping_address_address_line_1"
    t.string "shipping_address_address_line_2"
    t.boolean "is_prime"
    t.string "shipment_service_level_category"
    t.float "per_order_shipping_cost"
    t.string "per_order_shipping_cost_currency"
    t.index ["amazon_order_id"], name: "index_amazon_orders_on_amazon_order_id", unique: true
    t.index ["company_id"], name: "index_amazon_orders_on_company_id"
  end

  create_table "companies", options: "ENGINE=InnoDB DEFAULT CHARSET=latin1", force: :cascade do |t|
    t.string "name"
    t.string "address"
    t.string "city"
    t.string "state"
    t.string "zip"
    t.string "country"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "marketplace"
    t.string "merchant_id"
    t.string "mws_auth_token"
  end

  create_table "expenses", options: "ENGINE=InnoDB DEFAULT CHARSET=latin1", force: :cascade do |t|
    t.float "amount"
    t.string "expense_type"
    t.datetime "start_date"
    t.datetime "end_date"
    t.bigint "company_id"
    t.bigint "amazon_listing_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "description"
    t.string "currency"
    t.index ["amazon_listing_id"], name: "index_expenses_on_amazon_listing_id"
    t.index ["company_id"], name: "index_expenses_on_company_id"
  end

  create_table "users", options: "ENGINE=InnoDB DEFAULT CHARSET=latin1", force: :cascade do |t|
    t.string "username"
    t.string "first_name"
    t.string "last_name"
    t.string "email"
    t.string "password"
    t.bigint "company_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["company_id"], name: "index_users_on_company_id"
  end

  add_foreign_key "amazon_listings", "companies"
  add_foreign_key "amazon_orders", "companies"
  add_foreign_key "expenses", "amazon_listings"
  add_foreign_key "expenses", "companies"
  add_foreign_key "users", "companies"
end
