class SortUpFinancialEvents < ActiveRecord::Migration[5.2]
  def change
  	remove_column :amazon_financial_events, :event_type
  	add_column :amazon_financial_events, :type, :string
  	add_column :amazon_financial_events, :event_day, :date

  	add_column :amazon_financial_events, :amazon_order_id, :string
		add_column :amazon_financial_events, :seller_order_id, :string
		add_column :amazon_financial_events, :marketplace_name, :string
		add_column :amazon_financial_events, :posted_date, :datetime
		add_column :amazon_financial_events, :fee_total, :float
		add_column :amazon_financial_events, :fee_currency_code, :string
		add_column :amazon_financial_events, :marketplace_country_code, :string
		add_column :amazon_financial_events, :asin, :string
		add_column :amazon_financial_events, :total_amount_currency_amount, :float
		add_column :amazon_financial_events, :total_amount_currency_code, :string
		add_column :amazon_financial_events, :order_charge_total, :float
		add_column :amazon_financial_events, :order_charge_currency_code, :string
		add_column :amazon_financial_events, :order_charge_adjustment_total, :float
		add_column :amazon_financial_events, :order_charge_adjustment_currency_code, :string
		add_column :amazon_financial_events, :shipment_fee_total, :float
		add_column :amazon_financial_events, :shipment_fee_currency_code, :string
		add_column :amazon_financial_events, :shipment_fee_adjustment_total, :float
		add_column :amazon_financial_events, :shipment_fee_adjustment_currency_code, :string
		add_column :amazon_financial_events, :order_fee_total, :float
		add_column :amazon_financial_events, :order_fee_currency_code, :string
		add_column :amazon_financial_events, :order_fee_adjustment_total, :float
		add_column :amazon_financial_events, :order_fee_adjustment_currency_code, :string
		add_column :amazon_financial_events, :direct_payment_total, :float
		add_column :amazon_financial_events, :direct_payment_currency_code, :string
		add_column :amazon_financial_events, :shipment_item_skus, :string
		add_column :amazon_financial_events, :shipment_item_total, :float
		add_column :amazon_financial_events, :shipment_item_currency_code, :string
		add_column :amazon_financial_events, :transaction_posted_date, :string
		add_column :amazon_financial_events, :business_object_type, :string
		add_column :amazon_financial_events, :sales_channel, :string
		add_column :amazon_financial_events, :charge_type, :string
		add_column :amazon_financial_events, :charge_amount_currency_amount, :float
		add_column :amazon_financial_events, :charge_amount_currency_code, :string
		add_column :amazon_financial_events, :payment_amount_type, :string
		add_column :amazon_financial_events, :amount_description, :string
		add_column :amazon_financial_events, :fulfillment_channel, :string
		add_column :amazon_financial_events, :store_name, :string
		add_column :amazon_financial_events, :provider_transaction_type, :string
		add_column :amazon_financial_events, :marketplace_id, :string
		add_column :amazon_financial_events, :seller_id, :string
		add_column :amazon_financial_events, :seller_store_name, :string
		add_column :amazon_financial_events, :provider_id, :string
		add_column :amazon_financial_events, :provider_store_name, :string
		add_column :amazon_financial_events, :retrocharge_event_type, :string
		add_column :amazon_financial_events, :base_tax, :string
		add_column :amazon_financial_events, :shipping_tax, :string
		add_column :amazon_financial_events, :rental_event_type, :string
		add_column :amazon_financial_events, :extension_length, :string
		add_column :amazon_financial_events, :rental_charge_total, :float
		add_column :amazon_financial_events, :rental_charge_currency_code, :string
		add_column :amazon_financial_events, :rental_fee_total, :float
		add_column :amazon_financial_events, :rental_fee_currency_code, :string
		add_column :amazon_financial_events, :rental_initial_value_currency_amount, :float
		add_column :amazon_financial_events, :rental_initial_value_currency_code, :string
		add_column :amazon_financial_events, :rental_reimbursement_currency_amount, :float
		add_column :amazon_financial_events, :rental_reimbursement_currency_code, :string
		add_column :amazon_financial_events, :rental_tax_withheld_total, :float
		add_column :amazon_financial_events, :rental_tax_withheld_currency_code, :string
		add_column :amazon_financial_events, :amount_currency_amount, :float
		add_column :amazon_financial_events, :amount_currency_code, :string
		add_column :amazon_financial_events, :product_groups, :string
		add_column :amazon_financial_events, :transaction_type, :string
		add_column :amazon_financial_events, :invoice_id, :string
		add_column :amazon_financial_events, :base_value_currency_amount, :float
		add_column :amazon_financial_events, :base_value_currency_code, :string
		add_column :amazon_financial_events, :tax_value_currency_amount, :float
		add_column :amazon_financial_events, :tax_value_currency_code, :string
		add_column :amazon_financial_events, :transaction_value_currency_amount, :float
		add_column :amazon_financial_events, :transaction_value_currency_code, :string
		add_column :amazon_financial_events, :fee_reason, :string
		add_column :amazon_financial_events, :seller_sku, :string
		add_column :amazon_financial_events, :fn_sku, :string
		add_column :amazon_financial_events, :fee_description, :string
		add_column :amazon_financial_events, :debt_recovery_type, :string
		add_column :amazon_financial_events, :recovery_amount_currency_amount, :float
		add_column :amazon_financial_events, :recovery_amount_currency_code, :string
		add_column :amazon_financial_events, :over_payment_credit_currency_amount, :float
		add_column :amazon_financial_events, :over_payment_credit_currency_code, :string
		add_column :amazon_financial_events, :loan_amount_currency_amount, :float
		add_column :amazon_financial_events, :loan_amount_currency_code, :string
		add_column :amazon_financial_events, :source_business_event_type, :string
		add_column :amazon_financial_events, :adjustment_type, :string
		add_column :amazon_financial_events, :adjustment_amount_currency_amount, :float
		add_column :amazon_financial_events, :adjustment_amount_currency_code, :string
		add_column :amazon_financial_events, :adjustment_item_skus, :string
		add_column :amazon_financial_events, :coupon_id, :string
		add_column :amazon_financial_events, :seller_coupon_description, :string
		add_column :amazon_financial_events, :clip_or_redemption_count, :integer
		add_column :amazon_financial_events, :payment_event_id, :string
		add_column :amazon_financial_events, :safet_claim_id, :string
		add_column :amazon_financial_events, :reimbursed_amount_currency_amount, :float
		add_column :amazon_financial_events, :reimbursed_amount_currency_code, :float
		add_column :amazon_financial_events, :enrollment_id, :string
		add_column :amazon_financial_events, :parent_asin, :string
		add_column :amazon_financial_events, :original_removal_order_id, :string
		add_column :amazon_financial_events, :liquidation_proceeds_amount_currency_amount, :float
		add_column :amazon_financial_events, :liquidation_proceeds_amount_currency_code, :string
		add_column :amazon_financial_events, :liquidation_fee_amount_currency_amount, :float
		add_column :amazon_financial_events, :liquidation_fee_amount_currency_code, :string
		add_column :amazon_financial_events, :imaging_request_billing_item_id, :string
  end
end
